const textos = [
    'tabla', 'colchon', 'ganster', 'gradius', 'negrita', 'tijeras', 'trident', 'turista', 'rude',
    'apple', 'banana', 'carrot', 'dog', 'elephant', 'fish', 'grape', 'horse', 'iguana',
    'amarillo', 'azul', 'blanco', 'verde', 'rojo', '', 'negro', 'gris', 'marrón',
    'abogado', 'banco', 'coche', 'delfín', 'elefante', 'gato', 'hotel', 'iglesia', 'jirafa',
    'yellow', 'blue', 'white', 'green', 'red', 'orange', 'black', 'gray', 'brown',
    'lawyer', 'bank', 'car', 'dolphin', 'elephant', 'cat', 'hotel', 'church', 'giraffe',
    'casa', 'perro', 'gato', 'árbol', 'ciudad', 'montaña', 'río', 'playa', 'sol',
    'house', 'dog', 'cat', 'tree', 'city', 'mountain', 'river', 'beach', 'sun',
    'sol', 'luna', 'estrella', 'nube', 'lluvia', 'nieve', 'viento', 'tormenta', 'rayo',
    'sun', 'moon', 'star', 'cloud', 'rain', 'snow', 'wind', 'storm', 'lightning',
    'agua', 'fuego', 'tierra', 'aire', 'piedra', 'flor', 'fruta', 'vegetal', 'animal',
    'water', 'fire', 'earth', 'air', 'stone', 'flower', 'fruit', 'vegetable', 'animal',
    'manzana', 'pera', 'uva', 'fresa', 'limón', 'piña', 'sandía', 'melón',
    'apple', 'orange', 'pear', 'grape', 'strawberry', 'lemon', 'pineapple', 'watermelon', 'melon',
    'azucar', 'sal', 'aceite', 'harina', 'arroz', 'pan', 'carne', 'pescado', 'pollo',
    'sugar', 'salt', 'oil', 'flour', 'rice', 'bread', 'meat', 'fish', 'chicken',
    'leche', 'queso', 'huevos', 'yogur', 'crema', 'mantequilla', 'chocolate', 'azúcar', 'harina',
    'milk', 'cheese', 'eggs', 'yogurt', 'cream', 'butter', 'chocolate', 'sugar', 'flour',
    'amor', 'familia', 'amigos', 'pareja', 'beso', 'abrazo', 'felicidad', 'risa', 'llanto',
    'love', 'family', 'friends', 'couple', 'kiss', 'hug', 'happiness', 'laughter', 'tears',
    'casa', 'hogar', 'puerta', 'ventana', 'techo', 'suelo', 'pared', 'mueble', 'silla',
    'home', 'house', 'door', 'window', 'roof', 'floor', 'wall', 'furniture', 'chair',
    'guitarra', 'piano', 'violin', 'batería', 'flauta', 'trompeta', 'saxofón', 'instrumento', 'música',
    'guitar', 'piano', 'violin', 'drums', 'flute', 'trumpet', 'saxophone', 'instrument', 'music',
    'hombre', 'mujer', 'niño', 'niña', 'persona', 'adulto', 'joven', 'anciano', 'bebé',
    'man', 'woman', 'boy', 'girl', 'person', 'adult', 'youth', 'elderly', 'baby',
    'amigo', 'amiga', 'compañero', 'compañera', 'vecino', 'vecina', 'colega', 'conocido', 'desconocido',
    'friend', 'friend', 'colleague', 'neighbor', 'neighbor', 'colleague', 'acquaintance', 'stranger',
    'ropa', 'camisa', 'pantalón', 'vestido', 'falda', 'chaqueta', 'zapatos', 'calcetines', 'gorra',
    'clothing', 'shirt', 'pants', 'dress', 'skirt', 'jacket', 'shoes', 'socks', 'cap',
    'mañana', 'tarde', 'noche', 'día', 'semana', 'mes', 'año', 'hora', 'minuto',
    'morning', 'afternoon', 'evening', 'day', 'week', 'month', 'year', 'hour', 'minute',
    'solución', 'problema', 'pregunta', 'respuesta', 'tarea', 'examen', 'prueba', 'clase', 'escuela',
    'solution', 'problem', 'question', 'answer', 'task', 'exam', 'test', 'class', 'school',
    'computadora', 'teléfono', 'tableta', 'televisión', 'radio', 'internet', 'tecnología', 'red', 'cable',
    'computer', 'phone', 'tablet', 'television', 'radio', 'technology', 'network', 'cable',
    'arte', 'pintura', 'escultura', 'música', 'danza', 'teatro', 'literatura', 'poesía', 'cine',
    'art', 'painting', 'sculpture', 'music', 'dance', 'theater', 'literature', 'poetry', 'cinema',
    'fútbol', 'baloncesto', 'béisbol', 'tenis', 'golf', 'voleibol', 'natación', 'ciclismo', 'atletismo',
    'soccer', 'basketball', 'baseball', 'tennis', 'golf', 'volleyball', 'swimming', 'cycling', 'athletics',
    'huevo', 'pan', 'mantequilla', 'azúcar', 'sal', 'leche', 'café', 'té', 'zumo',
    'egg', 'bread', 'butter', 'sugar', 'salt', 'milk', 'coffee', 'tea', 'juice',
    'trabajo', 'dinero', 'éxito', 'fracaso', 'esfuerzo', 'descanso', 'vacaciones', 'tiempo', 'vida',
    'work', 'money', 'success', 'failure', 'effort', 'rest', 'vacations', 'time', 'life',
    'amor', 'odio', 'alegría', 'tristeza', 'ira', 'miedo', 'sorpresa', 'emoción', 'sentimiento',
    'love', 'hate', 'joy', 'anger', 'fear', 'surprise', 'excitement', 'feeling',
    'casa', 'hogar', 'puerta', 'ventana', 'techo', 'suelo', 'pared', 'mueble', 'silla',
    'home', 'house', 'door', 'window', 'roof', 'floor', 'wall', 'furniture', 'chair',
    'cama', 'almohada', 'sábana', 'manta', 'edredón', 'cobija', 'colchón', 'ropa', 'despertador',
    'bed', 'pillow', 'sheet', 'blanket', 'duvet', 'blanket', 'mattress', 'clothing', 'alarm clock',
    'sueño', 'descanso', 'insomnio', 'pesadilla', 'siesta', 'dormir', 'despertar', 'relajación', 'cansancio',
    'sleep', 'rest', 'insomnia', 'nightmare', 'nap', 'sleep', 'wake up', 'relaxation', 'tiredness',
    'agua', 'fuego', 'tierra', 'aire', 'mar', 'océano', 'río', 'lago', 'laguna',
    'water', 'fire', 'earth', 'air', 'sea', 'ocean', 'river', 'lake', 'lagoon',
    'montaña', 'colina', 'valle', 'desierto', 'bosque', 'selva', 'jungla', 'sabana', 'pradera',
    'mountain', 'hill', 'valley', 'desert', 'forest', 'jungle', 'jungle', 'savannah', 'meadow',
    'norte', 'sur', 'este', 'oeste', 'arriba', 'abajo', 'derecha', 'izquierda', 'adelante',
    'north', 'south', 'east', 'west', 'up', 'down', 'right', 'left', 'forward',
    'cielo', 'estrellas', 'luna', 'sol', 'nubes', 'rayo', 'tormenta', 'lluvia', 'nieve',
    'sky', 'stars', 'moon', 'sun', 'clouds', 'lightning', 'storm', 'rain', 'snow',
    'verano', 'invierno', 'primavera', 'otoño', 'calor', 'frío', 'temperatura', 'clima', 'meteorología',
    'summer', 'winter', 'spring', 'autumn', 'heat', 'cold', 'temperature', 'climate', 'meteorology',
    'ropa', 'zapatos', 'chaqueta', 'pantalón', 'camisa', 'falda', 'vestido', 'sombrero', 'bufanda',
    'clothing', 'shoes', 'jacket', 'pants', 'shirt', 'skirt', 'dress', 'hat', 'scarf',
    'amor', 'odio', 'alegría', 'tristeza', 'ira', 'miedo', 'sorpresa', 'emoción', 'sentimiento',
    'love', 'hate', 'joy', 'anger', 'fear', 'surprise', 'excitement', 'feeling',
    'feliz', 'triste', 'enojado', 'asustado', 'sorprendido', 'cansado', 'aburrido', 'emocionado', 'preocupado',
    'happy', 'sad', 'angry', 'scared', 'surprised', 'tired', 'bored', 'excited', 'worried',
    'comida', 'bebida', 'desayuno', 'almuerzo', 'cena', 'postre', 'fruta', 'verdura', 'carne',
    'food', 'drink', 'breakfast', 'lunch', 'dinner', 'fruit', 'vegetable', 'meat',
    'agua', 'vino', 'cerveza', 'refresco', 'jugo', 'leche', 'café', 'té', 'agua mineral',
    'water', 'wine', 'beer', 'soft drink', 'juice', 'milk', 'coffee', 'tea', 'mineral water',
    'ropa', 'camisa', 'pantalón', 'chaqueta', 'vestido', 'falda', 'zapatos', 'calcetines', 'corbata',
    'clothing', 'shirt', 'pants', 'jacket', 'dress', 'skirt', 'shoes', 'socks', 'tie',
    'ver', 'escuchar', 'hablar', 'escribir', 'leer', 'pensar', 'soñar', 'aprender', 'enseñar',
    'see', 'listen', 'speak', 'write', 'read', 'think', 'dream', 'learn', 'teach',
    'hacer', 'crear', 'dibujar', 'pintar', 'cantar', 'bailar', 'jugar', 'trabajar', 'estudiar',
    'do', 'create', 'draw', 'paint', 'sing', 'dance', 'play', 'work', 'study',
    'comer', 'beber', 'dormir', 'despertar', 'correr', 'caminar', 'nadar', 'saltar', 'volar',
    'eat', 'drink', 'sleep', 'wake up', 'run', 'walk', 'swim', 'jump', 'fly',
    'ir', 'venir', 'entrar', 'salir', 'subir', 'bajar', 'cruzar', 'pasar', 'viajar',
    'go', 'come', 'enter', 'exit', 'go up', 'go down', 'cross', 'pass', 'travel',
    'vivir', 'morir', 'nacer', 'crecer', 'envejecer', 'conocer', 'amor', 'odio', 'alegría',
    'live', 'die', 'be born', 'grow', 'age', 'know', 'love', 'hate', 'joy',
    'verde', 'amarillo', 'azul', 'rojo', '', 'negro', 'blanco', 'gris', 'marrón',
    'green', 'yellow', 'blue', 'red', 'orange', 'black', 'white', 'gray', 'brown',
    'uno', 'dos', 'tres', 'cuatro', 'cinco', 'seis', 'siete', 'ocho', 'nueve', 'diez',
    'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten',
    'uno', 'una', 'dos', 'tres', 'cuatro', 'cinco', 'seis', 'siete', 'ocho', 'nueve', 'diez',
    'one', 'a', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten',
    'más', 'menos', 'mayor', 'menor', 'igual', 'diferente', 'mejor', 'peor', 'primero', 'último',
    'more', 'less', '', 'smaller', 'equal', 'different', 'better', 'worse', 'first', 'last',
    'grande', 'pequeño', 'alto', 'bajo', 'largo', 'corto', 'ancho', 'estrecho', 'gordo', 'delgado',
    'big', 'small', 'tall', 'short', 'long', 'short', 'wide', 'narrow', 'fat', 'thin',
    'bien', 'mal', 'rápido', 'lento', 'duro', 'blando', 'fácil', 'difícil', 'alto', 'bajo',
    'well', 'bad', 'fast', 'slow', 'hard', 'soft', 'easy', 'difficult', 'high', 'low',
    'frío', 'caliente', 'calor', 'fresco', 'templado', 'congelado', 'helado', 'fuego', 'hielo',
    'cold', 'hot', 'heat', 'fresh', 'temperate', 'frozen', 'icy', 'fire', 'ice',
    'sol', 'luna', 'estrella', 'planeta', 'satélite', 'galaxia', 'universo', 'cosmos', 'espacio',
    'sun', 'moon', 'star', 'planet', 'satellite', 'galaxy', 'universe', 'cosmos', 'space',
    'tierra', 'aire', 'fuego', 'agua', 'metal', 'madera', 'plástico', 'vidrio', 'piedra', 'arena',
    'earth', 'air', 'fire', 'water', 'metal', 'wood', 'plastic', 'glass', 'stone', 'sand', 'perro', 'gato', 'pájaro', 'pez', 'conejo', 'tigre', 'león', 'elefante', 'jirafa', 'ratón',
    'dog', 'cat', 'bird', 'fish', 'rabbit', 'tiger', 'lion', 'elephant', 'giraffe', 'mouse',
    'rojo', 'azul', 'verde', 'amarillo', 'violeta', 'blanco', 'negro', 'gris', 'marrón',
    'red', 'blue', 'green', 'yellow', 'orange', 'violet', 'white', 'black', 'gray', 'brown',
    'casa', 'apartamento', 'villa', 'choza', 'mansión', 'cabaña', 'torre', 'bungalow', 'chalet', 'residencia',
    'house', 'apartment', 'villa', 'hut', 'mansion', 'cabin', 'tower', 'bungalow', 'cottage', 'residence',
    'amor', 'odio', 'felicidad', 'tristeza', 'alegría', 'ira', 'paz', 'guerra', 'esperanza', 'desesperación',
    'love', 'hate', 'happiness', 'joy', 'anger', 'peace', 'war', 'hope', 'desperation',
    'agua', 'fuego', 'aire', 'tierra', 'planta', 'animal', 'persona', 'mineral', 'vegetal', 'reino',
    'water', 'fire', 'air', 'earth', 'plant', 'animal', 'person', 'mineral', 'vegetable', 'kingdom',
    'azúcar', 'sal', 'vinagre', 'aceite', 'leche', 'chocolate', 'café', 'té', 'cerveza', 'vino',
    'sugar', 'salt', 'vinegar', 'oil', 'milk', 'chocolate', 'coffee', 'tea', 'beer', 'wine',
    'luz', 'oscuridad', 'sombra', 'brillo', 'resplandor', 'destello', 'rayo', 'sol', 'luna', 'estrella',
    'light', 'darkness', 'shadow', 'brightness', 'glow', 'sparkle', 'ray', 'sun', 'moon', 'star',
    'auto', 'camión', 'bicicleta', 'motocicleta', 'barco', 'avión', 'tren', 'autobús', 'metro', 'tranvía',
    'car', 'truck', 'bicycle', 'motorcycle', 'boat', 'airplane', 'train', 'bus', 'subway', 'tram',
    'ciencia', 'tecnología', 'ingeniería', 'matemáticas', 'física', 'química', 'biología', 'astronomía', 'geología', 'ecología',
    'science', 'technology', 'engineering', 'mathematics', 'physics', 'chemistry', 'biology', 'astronomy', 'geology', 'ecology',
    'verano', 'invierno', 'primavera', 'otoño', 'calor', 'frío', 'temperatura', 'clima', 'estación', 'solsticio',
    'summer', 'winter', 'spring', 'autumn', 'heat', 'cold', 'temperature', 'climate', 'season', 'solstice',
    'mundo', 'planeta', 'continente', 'océano', 'mar', 'tierra', 'luna', 'sol', 'estrella', 'galaxia',
    'world', 'planet', 'continent', 'ocean', 'sea', 'land', 'moon', 'sun', 'star', 'galaxy',
    'arte', 'música', 'pintura', 'escultura', 'danza', 'teatro', 'literatura', 'cine', 'fotografía', 'arte',
    'art', 'music', 'painting', 'sculpture', 'dance', 'theater', 'literature', 'cinema', 'photography', 'art',
    'historia', 'geografía', 'matemáticas', 'ciencia', 'literatura', 'música', 'arte', 'filosofía', 'religión', 'política',
    'history', 'geography', 'mathematics', 'science', 'literature', 'music', 'art', 'philosophy', 'religion', 'politics',
    'país', 'nación', 'estado', 'gobierno', 'territorio', 'capital', 'ciudad', 'pueblo', 'villa', 'aldea',
    'country', 'nation', 'state', 'government', 'territory', 'capital', 'city', 'town', 'village', 'village',
    'universidad', 'colegio', 'escuela', 'instituto', 'liceo', 'academia', 'aula', 'profesor', 'maestro', 'estudiante',
    'university', 'college', 'school', 'institute', 'high school', 'academy', 'classroom', 'teacher', 'teacher', 'student',
    'playa', 'océano', 'mar', 'arena', 'agua', 'olas', 'surf', 'nadar', 'sol', 'verano',
    'beach', 'ocean', 'sea', 'sand', 'water', 'waves', 'surf', 'swim', 'sun', 'summer',
    'padre', 'madre', 'hermano', 'hermana', 'hijo', 'hija', 'abuelo', 'abuela', 'tío', 'tía',
    'father', 'mother', 'brother', 'sister', 'son', 'daughter', 'grandfather', 'grandmother', 'uncle', 'aunt',
    'amar', 'besar', 'abrazar', 'acariciar', 'acariciar', 'apreciar', 'respetar', 'proteger', 'cuidar', 'compartir',
    'love', 'kiss', 'hug', 'caress', 'pet', 'appreciate', 'respect', 'protect', 'take care of', 'share',
    'hermoso', 'bello', 'lindo', 'guapo', 'atractivo', 'encantador', 'elegante', 'atractivo', 'impresionante', 'maravilloso',
    'beautiful', 'handsome', 'pretty', 'beautiful', 'attractive', 'charming', 'elegant', 'attractive', 'impressive', 'wonderful',
    'feliz', 'alegre', 'contento', 'divertido', 'sonriente', 'optimista', 'positivo', 'agradable', 'animado', 'entusiasta',
    'happy', 'cheerful', 'happy', 'fun', 'smiling', 'optimistic', 'positive', 'pleasant', 'lively', 'enthusiastic',
    'triste', 'infeliz', 'deprimido', 'abatido', 'melancólico', 'angustiado', 'solitario', 'desesperado', 'apenado', 'dolido',
    'sad', 'unhappy', 'depressed', 'downcast', 'melancholic', 'anguished', 'lonely', 'desperate', 'grieved', 'hurt',
    'aprendizaje', 'conocimiento', 'educación', 'escuela', 'clase', 'profesor', 'estudiante', 'maestro', 'académico', 'universidad',
    'learning', 'knowledge', 'education', 'school', 'class', 'teacher', 'teacher', 'academic', 'university',
    'pensamiento', 'idea', 'concepto', 'opinión', 'creencia', 'juicio', 'perspectiva', 'punto de vista', 'interpretación', 'entendimiento',
    'thought', 'idea', 'concept', 'opinion', 'belief', 'judgment', 'perspective', 'point of view', 'interpretation', 'understanding',
    'amistad', 'amor', 'compañerismo', 'solidaridad', 'confianza', 'respeto', 'apoyo', 'lealtad', 'compromiso', 'compania',
    'friendship', 'love', 'fellowship', 'solidarity', 'trust', 'respect', 'support', 'loyalty', 'commitment', 'companionship'
]

module.exports = textos;